---

- name: Creating logstash configuration file
  template: src=logstash.conf.j2 dest="{{ logstash_conf_dir }}/marvel.conf" owner=root group=root mode=0644
  notify:
    - restart logstash
  when: marvel_use_logstash
  tags:
    - marvel
    - logstash
